/*
 * This source file was generated by the Gradle 'init' task
 */
package org.texteditor;

import org.texteditor.window.WindowManager;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    @Override
    public void start(Stage primaryStage) {
        WindowManager windowManager = new WindowManager(primaryStage);

        windowManager.setup("My Application Window", "Welcome to JavaFX!", true);

        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
